sudo: required
services:
- docker
language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
- pypy-5.3.1
install:
- pip install .
- pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: fruch
  password:
    secure: eD+xiIt9Td8C2XRcDSLnS9e1ecoaKzQvbtlaqhYwD8v37QPW81cC044zI+28YAD9Y/0tLTPxJ358/y/qI9UMTZfUJTlK4BOsGUrG7ZhaHeH+oPpGVnISTYMNW1QSwIgiM3cuaos1YVqWDtSThJ25sf5IecQlCSjv9TrtQCtdv5k=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: fruch/paramiko-expect
